name: Build
on:
  push:
    tags:
      - 1.2.3
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir -p /tmp/asset/a/b/c/d/e/f/g
          echo 1 > /tmp/asset/a.txt
          echo 2 > /tmp/asset/a/b.txt
          echo 3 > /tmp/asset/a/b/c.txt
          echo 4 > /tmp/asset/a/b/c/d.xyz
          echo 5 > /tmp/asset/a/b/c/d/e.txt
          echo 6 > /tmp/asset/a/b/c/d/e/f.txt
          echo 7 > /tmp/asset/a/b/c/d/e/f/g.txt
          echo 111 > /tmp/asset/a/111
          echo 111 > /tmp/asset/666
          
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: /tmp/asset/*
