name: Build
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir -p /tmp/_output_assets/_output/kernel/assets
          mkdir -p /tmp/_output_assets/_output/kernel/kernel-6.12.1-repos/packages
          echo 1 > /tmp/_output_assets/_output/kernel/assets/1.txt
          echo 2 > /tmp/_output_assets/_output/kernel/kernel-6.12.1-repos/packages/2.txt
          echo 3 > /tmp/_output_assets/_output/kernel/kernel-6.12.1-repos/packages/3.txt

      - name: Generate release tag
        run: |
          echo "tgn=1.2.8" >> $GITHUB_ENV
          echo "$GITHUB_ENV"
          echo
          /bin/ls -la "$GITHUB_ENV"
          echo
          cat "$GITHUB_ENV"
          echo

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.tgn }}
          files: |
            /tmp/_output_assets/_output/kernel/assets/*
            /tmp/_output_assets/_output/kernel/kernel-**-repos/packages/*


          
